In [87]:
import pandas as pd
import numpy as np

In [88]:
df = pd.read_csv("BCHAIN-MKPRU_re.csv")
df.head()
# df[['ds','yhat']]
# yhat = df['yhat']
# # yhat.head()
# df['y'][0]
# ls = [0,2,1]
# ls.sort()
# print(ls[1])

          ds       y       syl
0  2016.9.12  609.67  0.002050
1  2016.9.13  610.92 -0.003437
2  2016.9.14  608.82  0.002562
3  2016.9.15  610.38 -0.002081
4  2016.9.16  609.11 -0.003398

In [106]:
shar = []
for i in range(30,len(df),30):
    rsyls = []
    for j in range(30):
        rsyls.append(df['syl'][i-j])

    rsyls_average = np.mean(rsyls)
    rsyls_biaozhucha = np.std(rsyls)
    # print(str(rsyls_average) + "     " +str(rsyls_biaozhucha) )
    # print(rsyls_biaozhucha)
    shar.append((rsyls_average-0.03)/rsyls_biaozhucha)

for i in shar:
    print(i)

-3.293816423488934
-1.2871998028818261
-2.1254706708875766
-0.5976271673489462
-0.7751972067823253
-0.814594541120954
-0.5680849911415903
-0.6519540874499058
-0.30107102842314326
-1.0109128358084252
-0.2323817726887695
-0.4784728677909722
-0.4878156006829497
-0.3911004080804958
0.01025391474863094
-0.38437553752913417
-0.879265722082661
-0.29852343130723213
-1.032571270227191
-0.43623973653497267
-1.2911665918727682
-1.0049322706950718
-0.9312132732990478
-1.301478129023771
-1.4887391690667031
-2.294942747434347
-1.0716587775170314
-0.9380290357502867
-1.6058528891128898
-0.9724406744333701
-2.2274564738275084
-0.5784430881566653
-0.28143147939379093
-0.3373602145634509
-0.651098968937351
-0.8170604214899122
-1.2234699911455778
-0.5977781980406233
-1.639395856705619
-1.004763777009388
-0.86235801675738
-0.8952069385559764
-0.4045915780253321
-0.6796805620326051
-0.5916670624359373
-0.9418780984904193
-2.2417756801819597
-0.7617170442957772
-1.2146755204219037
-1.1783623984508806
-0.5902952145448862
-0.5730269935031148
-0.32235299327599104
-0.2959644829544869
-0.5614482369057808
-1.036973591235153
-0.8219792277540323
-0.5338319136916215
-0.9068317960921978
-0.5059066590855499

In [89]:
import random
import math
fx = []
for i in range(30,len(df),30):
    ls = []
    for j in range(10000):
        xj = random.randint(0,30)
        s = df['y'][i] * math.exp(df['syl'][i-xj])
        ls.append(s)
    ls.sort()
    fx.append(ls[9000])

In [90]:
for i in fx:
    print(i)

640.8626829471198
742.6277541612444
788.0626244620321
944.282549392563
1005.9365465111827
1226.9085843454827
1290.5216855364065
1877.7941746763306
2996.361127921196
2624.1009485576783
3734.0968820256658
4952.2836174771655
4608.223048060612
7359.641348272054
15334.718872732354
19793.578789305302
8575.085727437647
11534.489581835209
7030.514644352546
10385.838554444712
7625.229148301542
6758.860047910728
7715.508459620349
7454.086405560378
6647.934141807662
6395.702942254491
4181.893122468224
3965.962050890745
3478.707333645452
3934.224890932399
4194.888785582019
5400.388461293545
9777.34718462575
13244.726322699727
10194.401730501366
10620.853417979888
8198.600969414929
9671.424676646302
7298.171453277391
7515.765833964426
8904.80887275316
10424.953088129234
7229.592709709598
7850.035380751301
9668.709662150735
10088.54737409901
9685.508667317605
11895.956616940122
11146.847422174178
12187.316447028446
18708.88074097859
25566.480162420157
39336.91688121284
55889.42921546293
61014.423714979304
58141.97590512495
44086.043557925936
42098.285144998554
32436.730946179632
48628.4245242382

In [95]:
import pandas as pd
import numpy as np

df1 = pd.read_excel("LBMA-GOLD_re_alltime.xlsx")
df2 = pd.read_excel("LBMA-GOLD_re_alltime.xlsx",sheet_name="Sheet1")
df1.fillna(method='ffill',inplace=True)
df1.to_csv("ffill.csv")
print(df1.head())
df2.head()

        Date  USD (PM)
0 2016-09-12   1324.60
1 2016-09-13   1323.65
2 2016-09-14   1321.75
3 2016-09-15   1310.80
4 2016-09-16   1308.35

           风险
0    0.000000
1  640.862683
2  737.874426
3  788.062624
4  942.309162

In [92]:
import numpy as np
fx = []
for i in df2['风险']:
    fx.append(i)

# print(fx)
p = []
for i in range(30,len(df1),30):
    pi =[]
    for j in range(0,30):
        pi.append(float(df1['USD (PM)'][i-j]))
    p.append(np.mean(pi))
print(p)

k = []
for i in range(len(p)):
    k.append(1/p[i])
print(k)

[1304.4283333333333, 1272.7733333333335, 1192.388333333333, 1147.7983333333332, 1205.6166666666666, 1232.8050000000003, 1241.4433333333332, 1261.7583333333337, 1258.8383333333334, 1245.5566666666668, 1247.861666666667, 1298.5233333333335, 1301.8483333333331, 1279.2950000000003, 1282.1383333333333, 1270.6083333333336, 1334.565, 1329.0916666666667, 1326.1466666666665, 1330.2599999999995, 1302.055, 1276.1416666666667, 1234.7533333333333, 1199.7616666666665, 1197.9033333333334, 1218.7216666666666, 1220.8766666666666, 1250.576666666667, 1288.9350000000002, 1319.8266666666664, 1301.49, 1285.5200000000002, 1282.8766666666668, 1355.1533333333339, 1412.2250000000001, 1489.346666666667, 1514.5033333333333, 1494.2266666666667, 1476.4, 1469.6266666666668, 1546.925, 1587.0800000000002, 1593.05, 1663.1283333333336, 1713.9066666666668, 1721.8049999999998, 1793.8300000000002, 1965.51, 1942.248333333333, 1896.4433333333332, 1893.3116666666667, 1836.9299999999998, 1873.9183333333333, 1832.5549999999996, 1735.8516666666665, 1736.8383333333334, 1807.3400000000001, 1878.5266666666669, 1794.3066666666666, 1791.175]
[0.0007666193492168344, 0.0007856858513691884, 0.000838652955622679, 0.0008712331870145599, 0.0008294510416522665, 0.000811158293485182, 0.0008055140119162374, 0.0007925447952922837, 0.0007943831813192851, 0.0008028538779180392, 0.0008013708784494006, 0.0007701055301278118, 0.0007681386336606032, 0.000781680534982158, 0.0007799470415958756, 0.0007870245879598353, 0.0007493078268949058, 0.0007523935519872595, 0.0007540644071545631, 0.0007517327439748624, 0.000768016712043654, 0.0007836120597896002, 0.0008098783562708881, 0.0008334988754711006, 0.0008347919002924554, 0.0008205318961261322, 0.0008190835547134164, 0.000799631103517577, 0.0007758343128241532, 0.0007576752502853912, 0.0007683501217834943, 0.0007778953264048788, 0.0007794981590851809, 0.000737923875772975, 0.000708102462426313, 0.0006714353497282923, 0.0006602824688401698, 0.0006692425067147331, 0.0006773232186399349, 0.0006804449202518553, 0.0006464437513130889, 0.000630087960279255, 0.0006277266878001318, 0.0006012765100307952, 0.0005834623433403608, 0.0005807858613489914, 0.0005574664265844589, 0.0005087738042543666, 0.0005148672200345133, 0.0005273028634303161, 0.0005281750583413366, 0.0005443865580071097, 0.0005336411850036155, 0.0005456862140563313, 0.0005760860903053353, 0.0005757588261429053, 0.0005532993238682262, 0.0005323320758466742, 0.0005573183328007848, 0.0005582927407986378]

In [93]:
g=[]
g.append(400/df1['USD (PM)'][0])
for i in range(1,len(k)):
    if df1['USD (PM)'][(i-1)*30] > df1['USD (PM)'][(i-1)*30]:
        g.append(0.95* k[i-1] * (fx[i]-fx[i-1]) + g[i-1])
    else:
        g.append(1.05* k[i-1] * (fx[i]-fx[i-1]) + g[i-1])

for i in range(len(g)):
    print(g[i])

flag = True
for i in range(len(g)-1):
    if  np.abs(g[i+1] - g[i]) < 0.01:
        flag = False
print(flag)

0.30197795560924057
0.8178405751944292
0.8978723666428422
0.9420673718630855
1.0831713094505928
1.162981530243509
1.3273293882823898
1.381132694850658
1.8370904295110186
2.89516157962682
2.4732806958754545
3.4220889978860436
4.407127956670567
4.129627430198044
6.472440349320358
12.919226587313418
16.482715715114924
7.771702175806821
10.109670372470536
6.543568821845069
9.289824203159718
6.963667893018307
6.250825753958228
7.144061510895937
6.833217979917512
6.126600130725163
5.909288199072055
4.005328221589549
3.8271292583711984
3.458706978300305
3.7903203673379684
4.000615559296494
4.9882117254232545
8.272112202611076
11.238503823230523
8.970564350548536
9.2712158253691
7.591876457131907
8.626836498397143
6.939004010902321
7.128665106143911
8.022970998940224
9.044321888740498
6.938218252733725
7.329928736847776
8.444113092745843
8.700140690264542
8.46422611523766
9.64507502829515
9.240098671253113
9.816173082175146
13.432927063680712
17.06313598797952
25.06295006806686
34.54705174630441
37.6471116925703
35.91058265445385
27.744587897208973
26.633532956861874
21.154579936620024
True